name: "Pull Request"

about: Create a pull request to contribute to this project.

title: "[Feature] - "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        ## PULL Request

        Is there an existing issue for this?
        - [ ] I have searched the existing issues

        ### Reference Issues
        Please list any reference issues related to this pull request:

  - type: input
    id: reference_issues
    attributes:
      label: Reference Issues
      description: Please list any reference issues related to this pull request.
      placeholder: "Add reference issue IDs or descriptions"

  - type: markdown
    attributes:
      value: |
        PULL_REQUEST.md
